
// UI Actions
export const SET_ACTIVE_SCREEN = 'SET_ACTIVE_SCREEN';
export const SHOW_TOAST = 'SHOW_TOAST';
export const CLEAR_TOAST = 'CLEAR_TOAST';
export const OPEN_PROFILE = 'OPEN_PROFILE';
export const CLOSE_PROFILE = 'CLOSE_PROFILE';
export const SHOW_PHASE_CHANGE_MODAL = 'SHOW_PHASE_CHANGE_MODAL';
export const DISMISS_PHASE_CHANGE_MODAL = 'DISMISS_PHASE_CHANGE_MODAL';
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const SET_BOTTOM_NAV_VISIBLE = 'SET_BOTTOM_NAV_VISIBLE';
export const SET_NAVIGATION_TARGET = 'SET_NAVIGATION_TARGET';
export const SET_MEAL_BUILDER_STATE = 'SET_MEAL_BUILDER_STATE';
export const SET_SYNC_STATUS = 'SET_SYNC_STATUS';

// Profile Actions
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_THEME = 'UPDATE_THEME';

// Progress Actions
export const START_CHALLENGE = 'START_CHALLENGE';
export const ADD_METRIC_ENTRY = 'ADD_METRIC_ENTRY';

// Workout Actions
export const ADD_USER_ROUTINE = 'ADD_USER_ROUTINE';
export const UPDATE_USER_ROUTINE = 'UPDATE_USER_ROUTINE';
export const DELETE_USER_ROUTINE = 'DELETE_USER_ROUTINE';
export const ADD_USER_EXERCISE = 'ADD_USER_EXERCISE';
export const UPDATE_USER_EXERCISE = 'UPDATE_USER_EXERCISE';
export const DELETE_USER_EXERCISE = 'DELETE_USER_EXERCISE';
export const ASSIGN_ROUTINE_TO_DAY = 'ASSIGN_ROUTINE_TO_DAY';
export const INCREMENT_CARDIO_WEEK = 'INCREMENT_CARDIO_WEEK';
export const ADD_SESSION_TO_HISTORY = 'ADD_SESSION_TO_HISTORY';
export const GENERATE_EXERCISE_IMAGE_START = 'GENERATE_EXERCISE_IMAGE_START';
export const GENERATE_EXERCISE_IMAGE_SUCCESS = 'GENERATE_EXERCISE_IMAGE_SUCCESS';
export const GENERATE_EXERCISE_IMAGE_FAILURE = 'GENERATE_EXERCISE_IMAGE_FAILURE';

// Nutrition Actions
export const REGISTER_MEAL = 'REGISTER_MEAL';
export const UPDATE_LOGGED_MEAL = 'UPDATE_LOGGED_MEAL';
export const DELETE_LOGGED_MEAL = 'DELETE_LOGGED_MEAL';
export const ADD_MY_RECIPE = 'ADD_MY_RECIPE';
export const UPDATE_MY_RECIPE = 'UPDATE_MY_RECIPE';
export const DELETE_MY_RECIPE = 'DELETE_MY_RECIPE';
export const ADD_CUSTOM_FOOD = 'ADD_CUSTOM_FOOD';
export const SAVE_USER_MODIFIED_FOOD = 'SAVE_USER_MODIFIED_FOOD';
export const RESET_EDITED_DEFAULT_FOOD = 'RESET_EDITED_DEFAULT_FOOD';
export const DELETE_CUSTOM_FOOD = 'DELETE_CUSTOM_FOOD';
export const TOGGLE_RECIPE_FAVORITE = 'TOGGLE_RECIPE_FAVORITE';

// Session Actions
export const START_ROUTINE = 'START_ROUTINE';
export const EXIT_ROUTINE = 'EXIT_ROUTINE';
export const PAUSE_ROUTINE = 'PAUSE_ROUTINE';
export const UPDATE_ACTIVE_ROUTINE_PROGRESS = 'UPDATE_ACTIVE_ROUTINE_PROGRESS';
export const SET_WORKOUT_SUMMARY = 'SET_WORKOUT_SUMMARY';
export const CLOSE_SUMMARY = 'CLOSE_SUMMARY';
export const SET_CARDIO_LOG_DATA = 'SET_CARDIO_LOG_DATA';
export const CLEAR_CARDIO_LOG_DATA = 'CLEAR_CARDIO_LOG_DATA';
export const COMPLETE_TASK = 'COMPLETE_TASK';
export const UNCOMPLETE_TASK = 'UNCOMPLETE_TASK';
export const UPDATE_DAILY_HABIT = 'UPDATE_DAILY_HABIT';
export const UPDATE_ACTIVE_ROUTINE_STATE = 'UPDATE_ACTIVE_ROUTINE_STATE';
export const RESET_DAILY_PROGRESS = 'RESET_DAILY_PROGRESS';
